- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Example assertion
      ansible.builtin.assert:
        that: true
    - name: Check if Jenkins is running.
      uri:
        url: "http://127.0.0.1:8085/"
        status_code: 200
#      register: result
#      until: result.status == 200
#      retries: 2
#      delay: 1