- hosts: localhost
  become: true


  vars:
    ansible_python_interpreter: /usr/bin/python3.10
#    jenkins_host: 127.0.0.1
    jenkins_port: 8085
    jenkins_admin_user: admin
    jenkins_admin_pass: admin
    java_packages:
      - openjdk-17-jdk
    jenkins_maven_installations:
      - 3.8.4
      - 3.9.0
    jenkins_job_config: "{{ lookup('template', 'job-config-2.xml.j2') }}"
    jenkins_maven_template: "{{ lookup('template', 'maven-install.groovy.j2') }}"
    jenkins_job_name: spipeline0

  pre_tasks:
    - include_vars: plugins.yml

  roles:
    - {role: geerlingguy.jenkins, jenkins_http_port: "{{ jenkins_port }}", jenkins_admin_username: "{{ jenkins_admin_user }}", jenkins_admin_password: "{{ jenkins_admin_pass }}", jenkins_plugins: "{{ plugins }}"}
    - {role: geerlingguy.java, become: yes, java_packages: openjdk-17-jdk}

  post_tasks:
#    - name: Add maven to Jenkins
#      community.general.jenkins_script:
#        script: "{{ jenkins_maven_template }}"
#        user: "{{ jenkins_admin_user }}"
#        password: "{{ jenkins_admin_pass}}"
#        url: "http://localhost:8085"
#        validate_certs: false
#        timeout: 120
#      with_items: jenkins_maven_installation
    - name: Create Jenkins pipeline job
      community.general.jenkins_job:
        config: "{{ jenkins_job_config }}"
        name: "{{ jenkins_job_name }}"
        user: "{{ jenkins_admin_user }}"
        password: "{{ jenkins_admin_pass}}"
        url: "http://localhost:8085"
        validate_certs: false
    - name: Get Jenkins pipeline job status
      community.general.jenkins_job_info:
        name: "{{ jenkins_job_name }}"
        user: "{{ jenkins_admin_user }}"
        password: "{{ jenkins_admin_pass}}"
        url: "http://localhost:8085"
        validate_certs: false
      retries: 3
      register: jenkins_job_info
#    - name: Build a project
#      uri:
#        url: "http://localhost:8085/buildByToken/buildWithParameters?token=newToken&job=spipeline2&CHECKSTYLE_RULES_SET=custom_checks&MAVEN_VERSION=maven3.9.0"
#        method: POST
#        user: "{{ jenkins_admin_user }}"
#        password: "{{ jenkins_admin_pass }}"
#        force_basic_auth: yes
#        status_code: 201
#        use_proxy: false
#        validate_certs: false
    - name: Get Jenkins pipeline job status after build
      community.general.jenkins_job_info:
        name: "{{ jenkins_job_name }}"
        user: "{{ jenkins_admin_user }}"
        password: "{{ jenkins_admin_pass }}"
        url: "http://localhost:8085"
        validate_certs: false
      retries: 3
      register: jenkins_job_info


